### PR TITLE
v0.5.0

### PR DESCRIPTION
**Pull request by manzt**
Publish v0.5

### CODE REVIEW

**Comment by manzt** [comment]
Hi! Apologies, I'll look into creating a CHANGELOG. The two primary changes are:

- Supporting an optional `"dimension_separator"` in `.zarray` metadata #89. This is a change to the zarr v2 spec, with a default of `"."` if the field is missing. There is more information about the change in the linked issues, but it shouldn't effect existing zarr arrays.

- Better error messages for unsupported dtypes #87

**Comment by guigrpa** [comment]
Thanks a lot!

**Comment by manzt** [comment]
Sorr - just got around to this #100!

**Comment by guigrpa** [comment]
No need to apologize **at all**. Your work has been fundamental to something really nice we're about to publish, so THANKS. I'll share more details when it's public! 😉

**Comment by manzt** [comment]
Excited to hear about it! Best of luck with the public release.

**Pull request merged**
