### PR TITLE
Add metadata for npm

### PR DESCRIPTION
**Pull request by manzt**
Adds description for npm with keywords.

### CODE REVIEW

**Comment by manzt** [comment]
I noticed that logo doesn't render and raw markdown shows up in search on npm:

project: 
https://www.npmjs.com/package/zarr

search:
https://www.npmjs.com/search?q=zarr

**Comment by gzuidhof** [comment]
Thanks. The logo not showing I think it's worth trying a jpeg yeah, here it is (converted by my OS, who knows what quality setting it is).
logo



What do you think of the logo? It reminds me of a shift keyboard button, not sure if that's a good or a bad thing

**Comment by manzt** [comment]
Ok -- when I find some time I'll try the jpeg. 

It's a great logo! I like the simplicity of the black and white, and it complements the current [zarr logo](https://github.com/zarr-developers/zarr-python/blob/master/README.md) well (with the nice `js` touch) :) 

I'm curious if adding a similar cube (perhaps without the grid lines like theirs) would quickly communicate that our project is in fact "that zarr" someone looking for a javascript implementation is thinking of.

**Comment by manzt** [comment]
I'm also noticing that `svgs` are supported on npm and github (see `d3` and `preact`). It would be my preference to use an svg of the logo if available! If you have an Illustrator file (or similar) please share. I would like to try a couple ideas!

**Comment by manzt** [comment]
I merged for now, and we can see if the current changes fix the rendering issue in the next release on npm (since the `README.md` won't update there until a new version is published).

I also separated the badges and logo onto new lines (as this might be involved?) and it doesn't change the rendering on GitHub. Perhaps we can use an svg for the next release as well, which will make sense once we are happy with #26.

**Pull request merged**
