### PR TITLE
Allow more data types (32 and 16 bit unsigned and signed ints)

### PR DESCRIPTION
**Pull request by ilan-gold**
Folllowing up on #3.  

Sorry about the linting - I can comment out the pre-commit hook or make a PR linting everything if it's too hard to read.  

The changes of interest are [here](https://github.com/gzuidhof/zarr.js/compare/master...ilan-gold:ilan-gold/add_typed_arrays?expand=1#diff-33f8b2e3fedb749a7d888a23baaed1f8R13-R21), [here](https://github.com/gzuidhof/zarr.js/compare/master...ilan-gold:ilan-gold/add_typed_arrays?expand=1#diff-33f8b2e3fedb749a7d888a23baaed1f8R41-R65), [here](https://github.com/gzuidhof/zarr.js/compare/master...ilan-gold:ilan-gold/add_typed_arrays?expand=1#diff-41df78d86ed4de80aae9b0b9560feb2bR18-R28), and [here](https://github.com/gzuidhof/zarr.js/compare/master...ilan-gold:ilan-gold/add_typed_arrays?expand=1#diff-084da47293fda649e6e1eb5d14f80a6aR142-R170)

### CODE REVIEW

**Comment by gzuidhof** [comment]
Thank you for your contribution :)
The PR is failing on lint on CI (see [here](https://travis-ci.org/gzuidhof/zarr.js/builds/634438768).
If you could resolve that (if you aren't using it already, VS Code should be able to help), I would love to merge this :)

**Comment by ilan-gold** [comment]
I am not using VS Code but I ran the tslint on the code.  Then when I commited, the pre-commit hook seems to have overriden my changes.  The previous commit is empty although `tslint` made these changes as far as I can tell:

Screen Shot 2020-01-10 at 1 05 30 PM
Screen Shot 2020-01-10 at 1 05 34 PM

**Comment by manzt** [comment]
I think I am having a similar issue here. I am using VSCode with `"source.fixAll.tslint": true`, which seems to be obeying the `tslint.json` config. But when committing changes, the husky pre-commit hooks performs linting which changes all the source.

I also notice that `package.json` has `prettier.semi === false` whereas tslint.config has `ruls.semicolon === [true, "always"]`.

**Comment by gzuidhof** [comment]
After fixing prettier and running it on all files, I decided to get rid of prettier altogether. It outputs ugly code when using a library like zarr (where internally it's not uncommon to call a function with 10+ arguments), it increased line count by >20%.

So I made this PR #9, if you rebase your branch (or merge master) this should now be fixed, there is no more precommit hook.

**Comment by gzuidhof** [comment]
Thanks for helping figure out the problem!

**Comment by ilan-gold** [comment]
@gzuidhof thanks for this!  i just pushed the changes so let me know if this looks good

**Pull request merged**
