### PR TITLE
Add fetchOptions and supportedMethods to HTTPStore

### PR DESCRIPTION
**Pull request by manzt**
If we just want to check if an item exists in a store, we can just make a requests for the headers (no body) and check the status code. However, this probably negates caching of these items in the browser, which might be a worse than what we have currently. Thoughts?

### CODE REVIEW

**Comment by gzuidhof** [comment]
This is a good idea, but I'm afraid that many webservers (or even cloud storage APIs) may not even listen to HEAD requests unless you explicitly tell it to. I think this should be togglable by the user when creating the http store. Something can be said for default on or off, I would say on.

**Comment by manzt** [comment]
Sorry for the delay on this -- what do you think about having a `supportedMethods` prop in the constructor?

The default could be `["GET", "HEAD"]` and or  `["GET", "HEAD", "PUT"]`? We could use this to throw more helpful error messages and decide what request type to use in contains item.

**Comment by gzuidhof** [comment]
That works I think :)

**Comment by manzt** [comment]
Sorry this has been so long... I'm not sure if I like the `supportedHeaders` API. It feels like it adds a good amount of complexity without much benefit. E.g. the only time `containsItem` gets called is to check for metadata, which is small generally in comparison. These requests aren't very frequent. 

However, I do think the `storageOptions` (which reflects the `zarr.FSStore` API) would address #60

**Comment by gzuidhof** [comment]
No worries about taking long, it's not a race :).

The PR looks good, the only thing I would change is to accept one options argument with two fields, instead of two new arguments. That will scale to an arbitrary amount of arguments and allow one to override any subset of defaults.

**Review by gzuidhof — APPROVED** [review]
See separate comment above ^

**Comment by manzt** [comment]
Kind of silly, I forgot about ES6 `Set`. I've changed the internal `supportedMethods` to be a `Set<HTTPMethod>` (rather than a `Map<HTTPMethod, boolean>`, which is much cleaner and what it is designed for! I've also consolidated the options into a single argument with two fields.

**Pull request merged**
