### PR TITLE
chore: Simplify testing

### PR DESCRIPTION
**Pull request by manzt**
Zarr.js has a bunch of dev dependencies that can be challenging to upgrade (#80 was somewhat painful). Specifically, the interplay between jest and ts-node/ts-jest is confusing. This PR strips out `ts-node` and `ts-jest` in favor of transpiling tests to JS using `babel`. This change removes type-checking from the test runner, but generally I think this is ok. We could always configure typescript to typecheck our tests as well.

The setup/teardown scripts can also be consolidated, and I was able to drop `serve-static` in favor of just using express.

@gzuidhof I won't merge without your approval. Zarr.js is basically dependency-less, and I'd prefer if the dev environment is also fairly uncomplicated :)

### CODE REVIEW

**Comment by manzt** [comment]
hmmm, this _was_ working locally. Need to investigate :)

**Comment by manzt** [comment]
I removed Node.js 10 from the testing suite because it is EOL. Since ESM has stabilized in node >= 12, i think it's fair to have our tests run as ESM.

**Comment by gzuidhof** [comment]
This is definitely an improvement 👍, not checking the types of test is fine and any simplification of testing is good. `tsc` command will tell us about issues anyway if we really want to (or your editor).

rant: I really wish there was a testing framework like Jest that would be for the browser natively, and only for Javascript (and not intended for E2E/UI testing like Cypress and friends). So many projects I end up having more dependencies for tests than the project itself..

**Comment by manzt** [comment]
> rant: I really wish there was a testing framework like Jest that would be for the browser natively, and only for Javascript (and not intended for E2E/UI testing like Cypress and friends). So many projects I end up having more dependencies for tests than the project itself..

I completely agree. This pain point generally means I write tests only for Node rather than trying to configure some browser configuration. But, I'm optimistic about ESM-first workflows. It's pretty amazing (considering the history of JS) that our ESM bundle for zarr can run in the browser, node, and deno now. Right now testing library and testing environment are too coupled (e.g. globals variables/functions in jest) so it's a configuration nightmare. I hope there is some ESM test runner, and then ideally changing the environment is just running the test suite (compiled to ESM). 

I think [`uvu`](https://github.com/lukeed/uvu) looks promising, combined with something like [`@web/test-runner`](https://modern-web.dev/docs/test-runner/overview/). That said, it's still config hell until someone packages these up nicely.

**Pull request merged**
